services:
- type: web
  name: axiom
  runtime: node
  repo: https://github.com/Glitch-Network/Axiom-Alpha
  branch: main
  plan: free
  region: oregon
  buildCommand: yarn
  startCommand: npm run start
  rootDir: ./
version: "1"